"""Added new columns to YourModel

Revision ID: 4249c8042906
Revises: 
Create Date: 2025-04-07 12:55:14.823672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4249c8042906'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('process', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('poc_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('poc_mobile_no', sa.BigInteger(), nullable=False))
        batch_op.create_unique_constraint(None, ['poc_name'])
        batch_op.create_unique_constraint(None, ['process'])
        batch_op.create_unique_constraint(None, ['poc_mobile_no'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('poc_mobile_no')
        batch_op.drop_column('poc_name')
        batch_op.drop_column('process')

    # ### end Alembic commands ###
